---
name: "Image: Rebuild"

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  push:
    branches:
      - main
    paths:
      - "apps/**"
      - "!apps/**/metadata.json"
      - "!apps/**/README.md"

jobs:
  get-changes:
    name: Collect changes
    runs-on: ubuntu-latest
    outputs:
      addedOrModifiedImages: ${{ steps.collect-changes.outputs.addedOrModifiedImages }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Collect changes
        id: collect-changes
        uses: ./.github/actions/collect-changes

  generate-build-matrix:
    name: Generate matrix for building images
    runs-on: ubuntu-latest
    needs: ["get-changes"]
    outputs:
      matrix: ${{ steps.get-changed.outputs.changes }}
    if: ${{ needs.get-changes.outputs.addedOrModifiedImages != '[]' && needs.get-changes.outputs.addedOrModifiedImages != '' }}
    steps:
      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      
      - name: Generate Token
        uses: tibdex/github-app-token@v2.1.0
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Fetch modified images
        id: get-changed
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const fetchAction = await import('${{ github.workspace }}/.github/scripts/index.mjs');
            let modifiedImages = ${{ needs.get-changes.outputs.addedOrModifiedImages }};
            let apps = modifiedImages.filter(Boolean);
            
            await fetchAction.appChanges(core, apps);

  images-build:
    uses: mmalyska/containers/.github/workflows/action-image-build.yaml@main
    needs:
      - generate-build-matrix
    with:
      imagesToBuild: "${{ needs.generate-build-matrix.outputs.matrix }}"
      pushImages: "true"
      updateMetadata: "true"
    secrets: inherit
