---
name: "Pull Request: Validate"

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  pr-metadata:
    uses: mmalyska/containers/.github/workflows/pr-metadata.yaml@main

  generate-build-matrix:
    name: Generate matrix for building images
    runs-on: ubuntu-latest
    needs: ["pr-metadata"]
    outputs:
      matrix: ${{ steps.get-changed.outputs.changes }}
    if: ${{ needs.pr-metadata.outputs.addedOrModifiedImages != '[]' && needs.pr-metadata.outputs.addedOrModifiedImages != '' }}
    steps:
      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Generate Token
        uses: tibdex/github-app-token@v2.1.0
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Fetch modified images
        id: get-changed
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const fetchAction = await import('${{ github.workspace }}/.github/scripts/index.mjs');
            let modifiedImages = ${{ needs.pr-metadata.outputs.addedOrModifiedImages }};
            let apps = modifiedImages.filter(Boolean);

            await fetchAction.appChanges(core, apps);

  images-build:
    uses: mmalyska/containers/.github/workflows/action-image-build.yaml@main
    needs: ["generate-build-matrix"]
    with:
      imagesToBuild: "${{ needs.generate-build-matrix.outputs.matrix }}"
      updateMetadata: "false"
    secrets: inherit
