---
name: "Manual Release"

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      apps:
        description: "Apps (ex: radarr,sonarr)"
        default: "ALL"
        required: true
      channels:
        description: "Channels (ex: main,develop)"
        default: "stable"
        required: true
      push:
        description: "Push"
        default: "false"
        required: true

env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generate-build-matrix:
    name: Generate matrix for building images
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.determine-images.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Generate Token
        uses: tibdex/github-app-token@0d49dd721133f900ebd5e0dff2810704e8defbc6 # v1.8.2
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Fetch new app versions
        id: determine-images
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const fetchAction = await import('${{ github.workspace }}/.github/scripts/index.mjs');
            const inputs = ${{ toJSON(inputs) }};
            let apps = inputs.apps
              .split(',')
              .filter(Boolean);
            let channels = inputs.channels
              .split(',')
              .filter(Boolean)
              .map(e => ({ "name": e, "stable": true }));
            if (apps == 'ALL') {
              await fetchAction.changes(glob, context, github, core, true);
            } else {
              await fetchAction.appChanges(core, apps, channels);
            }

  images-build:
    uses: mmalyska/containers/.github/workflows/action-image-build.yaml@main
    if: ${{ needs.generate-build-matrix.outputs.matrix != '[]' && needs.generate-build-matrix.outputs.matrix != '' }}
    needs: ["generate-build-matrix"]
    with:
      imagesToBuild: "${{ needs.generate-build-matrix.outputs.matrix }}"
      pushImages: "${{ github.event.inputs.push }}"
      updateMetadata: "${{ github.event.inputs.push }}"
    secrets: inherit
